# Generated by Django 3.0.6 on 2020-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200514_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-published_date',), 'verbose_name': 'quiz', 'verbose_name_plural': 'quizzes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='publish',
        ),
        migrations.AddField(
            model_name='quiz',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='published_date'),
        ),
    ]
