# Generated by Django 3.0.6 on 2020-05-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200514_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
